version: '3.8'
services:
  web:
    env_file: .env.development
    build:
      context: . #path to where to find docker file
      dockerfile: Dockerfile # name of docker file
    # command: go run src/main.go
    command: air src/main.go
    ports:
      - "3000:3000"
    volumes:
      - ".:/usr/src/app"
  db:
    image: postgres:alpine
    # env_file: .env.development
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db: