// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"time"
)

type Account struct {
	ID             int64     `json:"id"`
	DocumentNumber string    `json:"documentNumber"`
	CreatedAt      time.Time `json:"createdAt"`
}

type OperationsType struct {
	ID          int64     `json:"id"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"createdAt"`
}

type Transaction struct {
	ID            int64     `json:"id"`
	AccountID     int64     `json:"accountID"`
	OperationType int64     `json:"operationType"`
	Amount        string    `json:"amount"`
	EventDate     time.Time `json:"eventDate"`
}
